[package]
name = "gbe-proxy-common"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre.workspace = true
thiserror.workspace = true
color-eyre.workspace = true
tracing.workspace = true

quinn.workspace = true
rustls.workspace = true

bincode = "2.0.0-rc.3"
