name: CI
on: [push, pull_request]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10
  CI: 1


jobs:

  test:
    name: Test Suite
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - uses: taiki-e/install-action@nextest

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Compile tests
        run: cargo nextest run --all-features --workspace --no-run
      
      - name: Run tests
        run: cargo nextest run --all-features --workspace
